[tool.poetry] 
package-mode = false
readme = "README.md"

[make.up-block]
stuff = 3

[tool.poetry.dependencies]
python = "3.12.3"

[project]
name = "Scale Maker"

authors = [
  {name = "Takaya", email = "takaya@use.com"}
]
description = "Lovely Fractal!"
version=1.0
